"""Move proposers for daydream-chess.

The real GPT does not exist yet. ``MockProposer`` stands in behind a clean
``Proposer`` protocol so the model drops in later by swapping ~20 lines.

Design goal (contract / plan §6.2): the mock must reproduce the *temperature
dynamics* of a real sampled model so the demo's dreams-then-wake behaviour
holds:

  * temperature ≈ 0  → nearly always the SAME single move every resample, so an
    illegal top move repeats forever and the turn fails to wake.
  * temperature 0.8  → mostly legal, with ~2-4 illegal dreams first on average.
  * higher temperature → more and wilder dreams.

To get that, each move gets a deterministic logit:
  base preference (legal > force-applyable > phantom) + a fixed per-move jitter
seeded from the move string and a per-game seed. The jitter is *stable across
resamples from the same context* (so temp≈0 is deterministic) but *varies
between games*. The fresh randomness per resample comes only from the softmax
draw (``random.choices``).
"""

from __future__ import annotations

import math
import random
from typing import Protocol, runtime_checkable

import chess


@runtime_checkable
class Proposer(Protocol):
    """Interface the engine talks to. The real model will implement this too."""

    def sample_move(self, board: chess.Board, temperature: float) -> str:
        """Return ONE UCI move string sampled from the move-space.

        May be illegal — that's the whole point; illegal proposals become dreams.
        """
        ...


# Base logits, tuned so temperature 0.8 yields ~2-4 dreams before waking while
# temperature≈0 reliably locks onto a single (possibly illegal) move.
#   - legal moves should usually win, but not so dominantly that 0.8 never dreams.
#   - force-applyable (wrong_board) illegal moves are the "beautiful" dreams; give
#     them a meaningful but lower base so they show up before the wake.
#   - phantom moves are the wildest; lowest base so they're rarer.
# Tuned (see calibration below) so temp 0.8 averages ~3.6 dreams before waking,
# scaling monotonically: ~0.8 dreams at temp 0.2, ~1.9 at 0.5, ~5.9 at 1.2.
_BASE_LOGIT_LEGAL = 4.0
_BASE_LOGIT_WRONG_BOARD = 3.0
_BASE_LOGIT_PHANTOM = 1.0

# Jitter amplitude. Big enough that at 0.8 the ordering scatters (so different
# moves win on different resamples), small enough that the legal/illegal tiers
# still mostly hold.
_JITTER_AMPLITUDE = 2.5


class MockProposer:
    """Faithful stand-in for the GPT proposer.

    A ``seed`` makes a game's per-move jitter reproducible; pass ``None`` (default)
    for a fresh random game seed each construction.
    """

    def __init__(self, seed: int | None = None):
        # Per-game seed: fixes the jitter so resamples from the same context are
        # stable, while different games (different seeds) scatter differently.
        self._game_seed = random.randrange(2**31) if seed is None else seed
        # Independent RNG for the per-resample softmax draw so the draw doesn't
        # disturb (or get disturbed by) global random state.
        self._rng = random.Random(self._game_seed ^ 0x5DEECE66D)

    def _jitter(self, uci: str) -> float:
        """Deterministic, stable-per-(game, move) pseudo-random offset.

        NOT random.random(): seeded from the move string + game seed so it's the
        same on every resample within a game but varies between games.
        """
        h = hash((self._game_seed, uci)) & 0xFFFFFFFF
        # Map hash to [-amp, +amp].
        unit = (h / 0xFFFFFFFF) * 2.0 - 1.0
        return unit * _JITTER_AMPLITUDE

    def _candidate_space(self, board: chess.Board) -> list[tuple[str, float]]:
        """Build (uci, base_logit) candidates: all legal moves plus a sampling
        of plausible-but-illegal moves.

        Illegal candidates are generated by pairing every occupied from-square
        with a spread of destination squares (knight-ish + sliding offsets), then
        classifying each into the wrong_board / phantom tiers. This keeps the
        space plausible (real squares, real-looking moves) without exploding to
        all 64x64 pairs.
        """
        legal_ucis = {m.uci() for m in board.legal_moves}
        candidates: dict[str, float] = {}

        # Tier 1: every legal move.
        for uci in legal_ucis:
            candidates[uci] = _BASE_LOGIT_LEGAL

        # Tier 2 & 3: illegal-but-plausible. Offsets covering knight hops, single
        # and double steps, and a couple of diagonal/lateral slides.
        deltas = [
            (1, 2), (2, 1), (-1, 2), (-2, 1), (1, -2), (2, -1), (-1, -2), (-2, -1),
            (0, 1), (0, -1), (1, 0), (-1, 0), (0, 2), (0, -2),
            (1, 1), (-1, 1), (1, -1), (-1, -1), (2, 2), (-2, -2),
        ]
        for from_sq in chess.SQUARES:
            piece = board.piece_at(from_sq)
            ff, fr = chess.square_file(from_sq), chess.square_rank(from_sq)
            for df, dr in deltas:
                tf, tr = ff + df, fr + dr
                if not (0 <= tf < 8 and 0 <= tr < 8):
                    continue
                to_sq = chess.square(tf, tr)
                uci = chess.square_name(from_sq) + chess.square_name(to_sq)
                if uci in candidates:
                    continue  # already a legal move
                # Classify the from-square into a tier.
                if piece is not None and piece.color == chess.BLACK:
                    candidates[uci] = _BASE_LOGIT_WRONG_BOARD  # force-applyable
                else:
                    candidates[uci] = _BASE_LOGIT_PHANTOM  # empty / white piece

        return list(candidates.items())

    def sample_move(self, board: chess.Board, temperature: float) -> str:
        """Sample one UCI via softmax(logits / temperature) over the move-space."""
        candidates = self._candidate_space(board)
        # Degenerate (no moves at all): return a clearly phantom move.
        if not candidates:
            return "a1a1"

        ucis = [c[0] for c in candidates]
        logits = [base + self._jitter(uci) for uci, base in candidates]

        t = max(temperature, 1e-6)
        scaled = [lg / t for lg in logits]
        m = max(scaled)
        exps = [math.exp(s - m) for s in scaled]  # subtract max for stability
        total = sum(exps)
        weights = [e / total for e in exps]

        return self._rng.choices(ucis, weights=weights, k=1)[0]


# TODO: ModelProposer loads daydream-chess-nanogpt.pt here.
# It will implement the same `Proposer` protocol — `sample_move(board, temperature)`
# returning a UCI string sampled from the model's logits at the given temperature.
# Everything downstream (engine.play_model_turn, classify, the contract) is agnostic
# to which proposer is used, so swapping it in is a ~20-line change in app.py / game.py.
